# Configuration constants and default pricing rates for cloud cost calculator.
# Dynamically updated from AWS/Azure APIs when price changes are detected.

REGION_MAP = {'us-east-1': 'US East (N. Virginia)',
 'us-east-2': 'US East (Ohio)',
 'us-west-1': 'US West (N. California)',
 'us-west-2': 'US West (Oregon)',
 'af-south-1': 'Africa (Cape Town)',
 'ap-east-1': 'Asia Pacific (Hong Kong)',
 'ap-south-1': 'Asia Pacific (Mumbai)',
 'ap-northeast-3': 'Asia Pacific (Osaka)',
 'ap-northeast-2': 'Asia Pacific (Seoul)',
 'ap-southeast-1': 'Asia Pacific (Singapore)',
 'ap-southeast-2': 'Asia Pacific (Sydney)',
 'ap-northeast-1': 'Asia Pacific (Tokyo)',
 'ap-southeast-3': 'Asia Pacific (Jakarta)',
 'ap-southeast-4': 'Asia Pacific (Melbourne)',
 'ap-south-2': 'Asia Pacific (Hyderabad)',
 'ca-central-1': 'Canada (Central)',
 'eu-central-1': 'Europe (Frankfurt)',
 'eu-west-1': 'Europe (Ireland)',
 'eu-west-2': 'Europe (London)',
 'eu-south-1': 'Europe (Milan)',
 'eu-west-3': 'Europe (Paris)',
 'eu-south-2': 'Europe (Spain)',
 'eu-north-1': 'Europe (Stockholm)',
 'eu-central-2': 'Europe (Zurich)',
 'me-south-1': 'Middle East (Bahrain)',
 'me-central-1': 'Middle East (UAE)',
 'sa-east-1': 'South America (Sao Paulo)',
 'us-gov-east-1': 'AWS GovCloud (US-East)',
 'us-gov-west-1': 'AWS GovCloud (US-West)'}

PRICING_DEFAULTS = {'eks_cluster_hourly': 0.1,
 'datasync_rate': 0.0125,
 'drs_server_hourly': 0.028,
 'vpn_site_to_site_hourly': 0.05,
 'vpn_client_endpoint_hourly': 0.15,
 'vpn_client_connection_hourly': 0.05,
 'public_ip_hourly': 0.005,
 'aws_backup_snapshot_gb_rate': 0.05,
 'aws_efs_default_rates': {'standard': 0.36, 'ia': 0.0272, 'archive': 0.01},
 'fargate_default_rates': {'ap-southeast-3': {'vcpu': 0.0506,
                                              'memory': 0.00556},
                           'ap-southeast-1': {'vcpu': 0.04856,
                                              'memory': 0.005335},
                           'default': {'vcpu': 0.04048, 'memory': 0.004445}},
 'azure_public_ip_hourly': 0.005,
 'azure_nat_gateway_hourly': 0.045,
 'azure_nat_gateway_gb_rate': 0.045,
 'azure_vpn_gateway_base_hourly': 0.04,
 'azure_vpn_egress_gb_rate': 0.087,
 'azure_asr_monthly_per_instance': 25.0,
 'azure_backup_storage_gb_rate': 0.0224,
 'azure_files_default_rates': {'premium': 0.16,
                               'transaction-optimized': 0.06,
                               'hot': 0.024,
                               'cool': 0.015}}
